version: "3"

services:
  app:
    container_name: app
    build: ./app
    ports:
      - 3001:3001
    command: python3 app.py
    networks:
      - network
    tty: true
  locust:
    container_name: locust
    build: ./locust
    ports:
      - 3000:3000
    volumes:
      - ./locust:/locust
    entrypoint: "/bin/sh run.sh"
    environment:
      - HOST=app
      - MODE=GUI # Specify GUI or CUI
    depends_on:
      - app
    networks:
      - network
    tty: true

networks:
  network:
    driver: bridge